language: python

dist: xenial

python:
  - 3.6
  - 3.7

env:
  - NUMBA_DISABLE_JIT=1
<<<<<<< HEAD
  # - COVERALLS_PARALLEL=true
=======
>>>>>>> upstream/master

before_install:
  - sudo apt-get install ncompress

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
<<<<<<< HEAD
  - pip install sphinx
  - pip install sphinx_rtd_theme
=======
  - pip install PyYAML
  - pip install sphinx
  - pip install sphinx-rtd-theme
>>>>>>> upstream/master

script:
  - make docs
  - make test

after_success:
  - coveralls

notifications:
  - webhooks: https://coveralls.io/webhook
  - email: false
